---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    creator: krishna
    type: mydb

spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: krishna
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: myuser
...
